name: ci/cd

on:
  push:
    branches:
      - lab8
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: set up flutter
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run flutter analyze
        run: flutter analyze

  test:
    name: run tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: install dependencies
        run: flutter pub get

      - name: run flutter tests
        run: flutter test

  build_windows:
    name: build windows
    runs-on: windows-latest
    needs: [setup, analyze, test]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up for windows
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: install dependencies
        run: flutter pub get

      - name: enable win support
        run: flutter config --enable-windows-desktop

      - name: build desktop app
        run: flutter build windows --release

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release

